/**
 * Every state, union territory and district in India, for address entry.
 *
 * ## Why this is separate from `lib/mock/locations.ts`
 *
 * That module is the geography the platform *operates* in: districts with a
 * minimum order value, villages with coordinates, an `active` flag that decides
 * what dispatch and the coverage map will admit to. It is small on purpose,
 * and the counts on the public site are computed from it.
 *
 * This module is the administrative map of the country, and it exists for one
 * job: letting somebody in Sangli or Sonipat write down where they are when
 * they register. Merging the two would make "districts covered" mean 727, which
 * would be a claim rather than a count.
 *
 * So: address fields read from here, coverage and dispatch read from there, and
 * an account may name a district the platform has nobody in — which is a thing
 * operations needs to see, not a thing to prevent.
 *
 * ## Accuracy
 *
 * A snapshot, and districts are created often — several states have split
 * districts since this was compiled. It was cleaned against the position after
 * the 2019 and 2020 reorganisations: Ladakh separated from Jammu and Kashmir,
 * Dadra and Nagar Haveli merged with Daman and Diu, and Andaman and Nicobar
 * Islands added, none of which the source carried.
 *
 * When it goes stale, operations adds the district in Controls rather than
 * waiting for a deploy — the same escape hatch every other reference list here
 * has.
 *
 * Names are the current ones, with the source's parentheticals resolved:
 * "Mysuru (Mysore)" is stored as Mysuru. Where the bracket was the only thing
 * telling two districts apart it became a suffix instead — Telangana has
 * Warangal Rural and Warangal Urban, not two districts called Warangal.
 */

/** `[id, name, districts]`, sorted, so the file diffs sanely when it changes. */
type StateRow = readonly [string, string, readonly string[]];

const ROWS: readonly StateRow[] = [
  [
    "andaman-and-nicobar-islands",
    "Andaman and Nicobar Islands",
    ["Nicobar", "North and Middle Andaman", "South Andaman"],
  ],
  [
    "andhra-pradesh",
    "Andhra Pradesh",
    [
      "Anantapur",
      "Chittoor",
      "East Godavari",
      "Guntur",
      "Krishna",
      "Kurnool",
      "Nellore",
      "Prakasam",
      "Srikakulam",
      "Visakhapatnam",
      "Vizianagaram",
      "West Godavari",
      "YSR Kadapa",
    ],
  ],
  [
    "arunachal-pradesh",
    "Arunachal Pradesh",
    [
      "Anjaw",
      "Changlang",
      "Dibang Valley",
      "East Kameng",
      "East Siang",
      "Kra Daadi",
      "Kurung Kumey",
      "Lohit",
      "Longding",
      "Lower Dibang Valley",
      "Lower Siang",
      "Lower Subansiri",
      "Namsai",
      "Papum Pare",
      "Siang",
      "Tawang",
      "Tirap",
      "Upper Siang",
      "Upper Subansiri",
      "West Kameng",
      "West Siang",
    ],
  ],
  [
    "assam",
    "Assam",
    [
      "Baksa",
      "Barpeta",
      "Biswanath",
      "Bongaigaon",
      "Cachar",
      "Charaideo",
      "Chirang",
      "Darrang",
      "Dhemaji",
      "Dhubri",
      "Dibrugarh",
      "Dima Hasao",
      "Goalpara",
      "Golaghat",
      "Hailakandi",
      "Hojai",
      "Jorhat",
      "Kamrup",
      "Kamrup Metropolitan",
      "Karbi Anglong",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Majuli",
      "Morigaon",
      "Nagaon",
      "Nalbari",
      "Sivasagar",
      "Sonitpur",
      "South Salmara-Mankachar",
      "Tinsukia",
      "Udalguri",
      "West Karbi Anglong",
    ],
  ],
  [
    "bihar",
    "Bihar",
    [
      "Araria",
      "Arwal",
      "Aurangabad",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Bhojpur",
      "Buxar",
      "Darbhanga",
      "East Champaran",
      "Gaya",
      "Gopalganj",
      "Jamui",
      "Jehanabad",
      "Kaimur",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Lakhisarai",
      "Madhepura",
      "Madhubani",
      "Munger",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia",
      "Rohtas",
      "Saharsa",
      "Samastipur",
      "Saran",
      "Sheikhpura",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Vaishali",
      "West Champaran",
    ],
  ],
  ["chandigarh", "Chandigarh", ["Chandigarh"]],
  [
    "chhattisgarh",
    "Chhattisgarh",
    [
      "Balod",
      "Baloda Bazar",
      "Balrampur",
      "Bastar",
      "Bemetara",
      "Bijapur",
      "Bilaspur",
      "Dantewada",
      "Dhamtari",
      "Durg",
      "Gariyaband",
      "Janjgir-Champa",
      "Jashpur",
      "Kabirdham",
      "Kanker",
      "Kondagaon",
      "Korba",
      "Korea",
      "Mahasamund",
      "Mungeli",
      "Narayanpur",
      "Raigarh",
      "Raipur",
      "Rajnandgaon",
      "Sukma",
      "Surajpur",
      "Surguja",
    ],
  ],
  [
    "dadra-and-nagar-haveli-and-daman-and-diu",
    "Dadra and Nagar Haveli and Daman and Diu",
    ["Dadra & Nagar Haveli", "Daman", "Diu"],
  ],
  [
    "delhi",
    "Delhi",
    [
      "Central Delhi",
      "East Delhi",
      "New Delhi",
      "North Delhi",
      "North East Delhi",
      "North West Delhi",
      "Shahdara",
      "South Delhi",
      "South East Delhi",
      "South West Delhi",
      "West Delhi",
    ],
  ],
  ["goa", "Goa", ["North Goa", "South Goa"]],
  [
    "gujarat",
    "Gujarat",
    [
      "Ahmedabad",
      "Amreli",
      "Anand",
      "Aravalli",
      "Banaskantha",
      "Bharuch",
      "Bhavnagar",
      "Botad",
      "Chhota Udepur",
      "Dahod",
      "Dangs",
      "Devbhoomi Dwarka",
      "Gandhinagar",
      "Gir Somnath",
      "Jamnagar",
      "Junagadh",
      "Kachchh",
      "Kheda",
      "Mahisagar",
      "Mehsana",
      "Morbi",
      "Narmada",
      "Navsari",
      "Panchmahal",
      "Patan",
      "Porbandar",
      "Rajkot",
      "Sabarkantha",
      "Surat",
      "Surendranagar",
      "Tapi",
      "Vadodara",
      "Valsad",
    ],
  ],
  [
    "haryana",
    "Haryana",
    [
      "Ambala",
      "Bhiwani",
      "Charkhi Dadri",
      "Faridabad",
      "Fatehabad",
      "Gurgaon",
      "Hisar",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Karnal",
      "Kurukshetra",
      "Mahendragarh",
      "Mewat",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamunanagar",
    ],
  ],
  [
    "himachal-pradesh",
    "Himachal Pradesh",
    [
      "Bilaspur",
      "Chamba",
      "Hamirpur",
      "Kangra",
      "Kinnaur",
      "Kullu",
      "Lahaul &amp; Spiti",
      "Mandi",
      "Shimla",
      "Sirmaur",
      "Solan",
      "Una",
    ],
  ],
  [
    "jammu-and-kashmir",
    "Jammu and Kashmir",
    [
      "Anantnag",
      "Bandipore",
      "Baramulla",
      "Budgam",
      "Doda",
      "Ganderbal",
      "Jammu",
      "Kargil",
      "Kathua",
      "Kishtwar",
      "Kulgam",
      "Kupwara",
      "Leh",
      "Poonch",
      "Pulwama",
      "Rajouri",
      "Ramban",
      "Reasi",
      "Samba",
      "Shopian",
      "Srinagar",
      "Udhampur",
    ],
  ],
  [
    "jharkhand",
    "Jharkhand",
    [
      "Bokaro",
      "Chatra",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "East Singhbhum",
      "Garhwa",
      "Giridih",
      "Godda",
      "Gumla",
      "Hazaribag",
      "Jamtara",
      "Khunti",
      "Koderma",
      "Latehar",
      "Lohardaga",
      "Pakur",
      "Palamu",
      "Ramgarh",
      "Ranchi",
      "Sahibganj",
      "Seraikela-Kharsawan",
      "Simdega",
      "West Singhbhum",
    ],
  ],
  [
    "karnataka",
    "Karnataka",
    [
      "Bagalkot",
      "Ballari",
      "Belagavi",
      "Bengaluru Rural",
      "Bengaluru Urban",
      "Bidar",
      "Chamarajanagar",
      "Chikballapur",
      "Chikkamagaluru",
      "Chitradurga",
      "Dakshina Kannada",
      "Davangere",
      "Dharwad",
      "Gadag",
      "Hassan",
      "Haveri",
      "Kalaburagi",
      "Kodagu",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysuru",
      "Raichur",
      "Ramanagara",
      "Shivamogga",
      "Tumakuru",
      "Udupi",
      "Uttara Kannada",
      "Vijayapura",
      "Yadgir",
    ],
  ],
  [
    "kerala",
    "Kerala",
    [
      "Alappuzha",
      "Ernakulam",
      "Idukki",
      "Kannur",
      "Kasaragod",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Palakkad",
      "Pathanamthitta",
      "Thiruvananthapuram",
      "Thrissur",
      "Wayanad",
    ],
  ],
  ["ladakh", "Ladakh", ["Kargil", "Leh"]],
  [
    "lakshadweep",
    "Lakshadweep",
    [
      "Agatti",
      "Amini",
      "Androth",
      "Bithra",
      "Chethlath",
      "Kadmath",
      "Kalpeni",
      "Kavaratti",
      "Kilthan",
      "Minicoy",
    ],
  ],
  [
    "madhya-pradesh",
    "Madhya Pradesh",
    [
      "Agar Malwa",
      "Alirajpur",
      "Anuppur",
      "Ashoknagar",
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Burhanpur",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Dewas",
      "Dhar",
      "Dindori",
      "Guna",
      "Gwalior",
      "Harda",
      "Hoshangabad",
      "Indore",
      "Jabalpur",
      "Jhabua",
      "Katni",
      "Khandwa",
      "Khargone",
      "Mandla",
      "Mandsaur",
      "Morena",
      "Narsinghpur",
      "Neemuch",
      "Panna",
      "Raisen",
      "Rajgarh",
      "Ratlam",
      "Rewa",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sheopur",
      "Shivpuri",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Umaria",
      "Vidisha",
    ],
  ],
  [
    "maharashtra",
    "Maharashtra",
    [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Beed",
      "Bhandara",
      "Buldhana",
      "Chandrapur",
      "Dhule",
      "Gadchiroli",
      "Gondia",
      "Hingoli",
      "Jalgaon",
      "Jalna",
      "Kolhapur",
      "Latur",
      "Mumbai City",
      "Mumbai Suburban",
      "Nagpur",
      "Nanded",
      "Nandurbar",
      "Nashik",
      "Osmanabad",
      "Palghar",
      "Parbhani",
      "Pune",
      "Raigad",
      "Ratnagiri",
      "Sangli",
      "Satara",
      "Sindhudurg",
      "Solapur",
      "Thane",
      "Wardha",
      "Washim",
      "Yavatmal",
    ],
  ],
  [
    "manipur",
    "Manipur",
    [
      "Bishnupur",
      "Chandel",
      "Churachandpur",
      "Imphal East",
      "Imphal West",
      "Jiribam",
      "Kakching",
      "Kamjong",
      "Kangpokpi",
      "Noney",
      "Pherzawl",
      "Senapati",
      "Tamenglong",
      "Tengnoupal",
      "Thoubal",
      "Ukhrul",
    ],
  ],
  [
    "meghalaya",
    "Meghalaya",
    [
      "East Garo Hills",
      "East Jaintia Hills",
      "East Khasi Hills",
      "North Garo Hills",
      "Ri Bhoi",
      "South Garo Hills",
      "South West Garo Hills",
      "South West Khasi Hills",
      "West Garo Hills",
      "West Jaintia Hills",
      "West Khasi Hills",
    ],
  ],
  [
    "mizoram",
    "Mizoram",
    [
      "Aizawl",
      "Champhai",
      "Kolasib",
      "Lawngtlai",
      "Lunglei",
      "Mamit",
      "Saiha",
      "Serchhip",
    ],
  ],
  [
    "nagaland",
    "Nagaland",
    [
      "Dimapur",
      "Kiphire",
      "Kohima",
      "Longleng",
      "Mokokchung",
      "Mon",
      "Peren",
      "Phek",
      "Tuensang",
      "Wokha",
      "Zunheboto",
    ],
  ],
  [
    "odisha",
    "Odisha",
    [
      "Angul",
      "Balangir",
      "Balasore",
      "Bargarh",
      "Bhadrak",
      "Boudh",
      "Cuttack",
      "Deogarh",
      "Dhenkanal",
      "Gajapati",
      "Ganjam",
      "Jagatsinghapur",
      "Jajpur",
      "Jharsuguda",
      "Kalahandi",
      "Kandhamal",
      "Kendrapara",
      "Kendujhar",
      "Khordha",
      "Koraput",
      "Malkangiri",
      "Mayurbhanj",
      "Nabarangpur",
      "Nayagarh",
      "Nuapada",
      "Puri",
      "Rayagada",
      "Sambalpur",
      "Sonepur",
      "Sundargarh",
    ],
  ],
  ["puducherry", "Puducherry", ["Karaikal", "Mahe", "Pondicherry", "Yanam"]],
  [
    "punjab",
    "Punjab",
    [
      "Amritsar",
      "Barnala",
      "Bathinda",
      "Faridkot",
      "Fatehgarh Sahib",
      "Fazilka",
      "Ferozepur",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Ludhiana",
      "Mansa",
      "Moga",
      "Muktsar",
      "Nawanshahr",
      "Pathankot",
      "Patiala",
      "Rupnagar",
      "Sahibzada Ajit Singh Nagar",
      "Sangrur",
      "Tarn Taran",
    ],
  ],
  [
    "rajasthan",
    "Rajasthan",
    [
      "Ajmer",
      "Alwar",
      "Banswara",
      "Baran",
      "Barmer",
      "Bharatpur",
      "Bhilwara",
      "Bikaner",
      "Bundi",
      "Chittorgarh",
      "Churu",
      "Dausa",
      "Dholpur",
      "Dungarpur",
      "Hanumangarh",
      "Jaipur",
      "Jaisalmer",
      "Jalore",
      "Jhalawar",
      "Jhunjhunu",
      "Jodhpur",
      "Karauli",
      "Kota",
      "Nagaur",
      "Pali",
      "Pratapgarh",
      "Rajsamand",
      "Sawai Madhopur",
      "Sikar",
      "Sirohi",
      "Sri Ganganagar",
      "Tonk",
      "Udaipur",
    ],
  ],
  [
    "sikkim",
    "Sikkim",
    ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
  ],
  [
    "tamil-nadu",
    "Tamil Nadu",
    [
      "Ariyalur",
      "Chennai",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Kanchipuram",
      "Kanyakumari",
      "Karur",
      "Krishnagiri",
      "Madurai",
      "Nagapattinam",
      "Namakkal",
      "Nilgiris",
      "Perambalur",
      "Pudukkottai",
      "Ramanathapuram",
      "Salem",
      "Sivaganga",
      "Thanjavur",
      "Theni",
      "Thoothukudi",
      "Tiruchirappalli",
      "Tirunelveli",
      "Tiruppur",
      "Tiruvallur",
      "Tiruvannamalai",
      "Tiruvarur",
      "Vellore",
      "Viluppuram",
      "Virudhunagar",
    ],
  ],
  [
    "telangana",
    "Telangana",
    [
      "Adilabad",
      "Bhadradri Kothagudem",
      "Hyderabad",
      "Jagtial",
      "Jangaon",
      "Jayashankar Bhoopalpally",
      "Jogulamba Gadwal",
      "Kamareddy",
      "Karimnagar",
      "Khammam",
      "Komaram Bheem Asifabad",
      "Mahabubabad",
      "Mahabubnagar",
      "Mancherial",
      "Medak",
      "Medchal",
      "Nagarkurnool",
      "Nalgonda",
      "Nirmal",
      "Nizamabad",
      "Peddapalli",
      "Rajanna Sircilla",
      "Rangareddy",
      "Sangareddy",
      "Siddipet",
      "Suryapet",
      "Vikarabad",
      "Wanaparthy",
      "Warangal Rural",
      "Warangal Urban",
      "Yadadri Bhuvanagiri",
    ],
  ],
  [
    "tripura",
    "Tripura",
    [
      "Dhalai",
      "Gomati",
      "Khowai",
      "North Tripura",
      "Sepahijala",
      "South Tripura",
      "Unakoti",
      "West Tripura",
    ],
  ],
  [
    "uttar-pradesh",
    "Uttar Pradesh",
    [
      "Agra",
      "Aligarh",
      "Allahabad",
      "Ambedkar Nagar",
      "Amethi",
      "Amroha",
      "Auraiya",
      "Azamgarh",
      "Baghpat",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Barabanki",
      "Bareilly",
      "Basti",
      "Bhadohi",
      "Bijnor",
      "Budaun",
      "Bulandshahr",
      "Chandauli",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Etawah",
      "Faizabad",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Gautam Buddha Nagar",
      "Ghaziabad",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hapur",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur Dehat",
      "Kanpur Nagar",
      "Kanshiram Nagar",
      "Kaushambi",
      "Kushinagar",
      "Lakhimpur - Kheri",
      "Lalitpur",
      "Lucknow",
      "Maharajganj",
      "Mahoba",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "RaeBareli",
      "Rampur",
      "Saharanpur",
      "Sambhal",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shamali",
      "Shravasti",
      "Siddharth Nagar",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi",
    ],
  ],
  [
    "uttarakhand",
    "Uttarakhand",
    [
      "Almora",
      "Bageshwar",
      "Chamoli",
      "Champawat",
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Pauri Garhwal",
      "Pithoragarh",
      "Rudraprayag",
      "Tehri Garhwal",
      "Udham Singh Nagar",
      "Uttarkashi",
    ],
  ],
  [
    "west-bengal",
    "West Bengal",
    [
      "Alipurduar",
      "Bankura",
      "Birbhum",
      "Burdwan",
      "Cooch Behar",
      "Dakshin Dinajpur",
      "Darjeeling",
      "Hooghly",
      "Howrah",
      "Jalpaiguri",
      "Kalimpong",
      "Kolkata",
      "Malda",
      "Murshidabad",
      "Nadia",
      "North 24 Parganas",
      "Paschim Medinipur",
      "Purba Medinipur",
      "Purulia",
      "South 24 Parganas",
      "Uttar Dinajpur",
    ],
  ],
];

export interface IndianState {
  readonly id: string;
  readonly name: string;
  readonly districts: readonly string[];
}

export const INDIAN_STATES: readonly IndianState[] = ROWS.map(
  ([id, name, districts]) => ({ id, name, districts }),
);

const BY_ID = new Map(INDIAN_STATES.map((state) => [state.id, state]));

export function stateById(id: string): IndianState | undefined {
  return BY_ID.get(id);
}

/** The districts of one state, or nothing for an id that is not a state. */
export function districtsOf(stateId: string): readonly string[] {
  return BY_ID.get(stateId)?.districts ?? [];
}

/**
 * Whether a district belongs to the state it was submitted with.
 *
 * Checked on the server as well as in the form: the pair arrives from a
 * browser, and "Erode, Punjab" would otherwise be stored and then shown to
 * operations as though somebody had meant it.
 */
export function isDistrictOf(stateId: string, district: string): boolean {
  const wanted = district.trim().toLowerCase();
  return districtsOf(stateId).some((name) => name.toLowerCase() === wanted);
}

/**
 * Which state a district is in, where the answer is not ambiguous.
 *
 * District names are not unique across India — there is an Aurangabad in
 * Maharashtra and another in Bihar, a Bilaspur in Himachal and another in
 * Chhattisgarh, a Hamirpur in two states. So this returns `undefined` for a
 * name that appears more than once rather than picking whichever state comes
 * first in the list.
 *
 * That matters here because the caller is choosing which state's mandi rates
 * to show somebody. Falling back to a default is a mild loss; confidently
 * showing a farmer in Bihar the rates from Maharashtra is a wrong number
 * presented as a right one.
 *
 * Built once at module load — this is a linear scan over seven hundred
 * districts and the ticker asks on every request.
 */
const STATE_BY_DISTRICT: ReadonlyMap<string, string | null> = (() => {
  const found = new Map<string, string | null>();

  for (const state of INDIAN_STATES) {
    for (const district of state.districts) {
      const key = district.trim().toLowerCase();
      // `null` marks a name claimed by more than one state.
      found.set(key, found.has(key) ? null : state.name);
    }
  }

  return found;
})();

export function stateNameForDistrict(district: string): string | undefined {
  if (!district) return undefined;
  return STATE_BY_DISTRICT.get(district.trim().toLowerCase()) ?? undefined;
}

/** Districts whose name is used by more than one state. */
export function isAmbiguousDistrict(district: string): boolean {
  return STATE_BY_DISTRICT.get(district.trim().toLowerCase()) === null;
}
